contact: '# Contact

  You may contact us through [our team mail address](mailto:steamghent@gmail.com)
  if you have any questions or would like to bring up any issues. You can also find
  us on the following location

  - UGent Campus Ardoyen

  - Technologiepark-Zwijnaarde 122

  - 9052 Ghent (Zwijnaarde)

  '
disqus:
  comments: false
  disqus_shortname: thathungrymind
google-analytics-ua: UA-112060364-3
logo:
  url: ./img/triangle.png
menu:
- name: Projects
  url: ''
projects:
- file: projects/daiquiri.html
  folder: DAIQUIRI
  lead_researcher: jelledb
  name: DAIQUIRI
  research_supervisor:
  - stevenvs
  tags:
  - past
  - sports
- file: projects/smartglaz.html
  folder: SMARTGLAZ
  lead_researcher: jelledb
  name: SMARTGLAZ
  research_supervisor:
  - stevenvs
  tags:
  - past
  - geospatial
- file: projects/flore-de-gand.html
  folder: FLORE-DE-GAND
  lead_researcher: krishnaku
  name: FLORE DE GAND
  research_supervisor:
  - stevenvs
  tags:
  - past
  - cultural-heritage
- file: projects/hasard.html
  folder: HASARD
  lead_researcher: stevenvs
  name: HASARD
  other_researchers:
  - jelledb
  tags:
  - past
  - sports
- file: projects/spott.html
  folder: SPOTT
  lead_researcher: krishnaku
  name: SPOTT
  research_supervisor:
  - stevenvs
  tags:
  - past
  - cultural-heritage
- file: projects/koers.html
  folder: KOERS
  lead_researcher: jelledb
  name: KOERS
  research_supervisor:
  - stevenvs
  tags:
  - past
  - sports
- file: projects/bas-x.html
  folder: BAS-X
  lead_researcher: kenzomv
  name: BAS-X
  other_researchers:
  - jelledb
  research_supervisor:
  - stevenvs
  tags:
  - past
  - geospatial
- file: projects/tobias.html
  folder: TOBIAS
  lead_researcher: jellevh
  name: TOBIAS
  research_supervisor:
  - stevenvs
  tags:
  - past
  - industry
- file: projects/smart-waterways.html
  folder: SMART-WATERWAYS
  lead_researcher: krishnaku
  name: SMART WATERWAYS
  other_researchers:
  - dilawaral
  research_supervisor:
  - stevenvs
  tags:
  - past
  - industry
- file: projects/bioracer.html
  folder: BIORACER
  lead_researcher: jarichb
  name: BIORACER
  other_researchers:
  - jelledb
  research_supervisor:
  - stevenvs
  tags:
  - past
  - sports
- file: projects/ugesco.html
  folder: UGESCO
  lead_researcher: kenzomv
  name: UGESCO
  other_researchers:
  - dilawaral
  research_supervisor:
  - stevenvs
  tags:
  - past
  - cultural-heritage
  - geospatial
- file: projects/eureca.html
  folder: EURECA
  lead_researcher: kenzomv
  other_researchers:
  - dilawaral
  name: EURECA
  research_supervisor:
  - stevenvs
  tags:
  - past
  - cultural-heritage
- file: projects/DATA-KBR-BE.html
  folder: DATA-KBR-BE
  lead_researcher: dilawaral
  other_researchers:
  - kenzomv
  name: DATA-KBR-BE
  research_supervisor:
  - stevenvs
  tags:
  - past
  - cultural-heritage
- file: projects/COURSE.html
  folder: COURSE
  lead_researcher: rodcorte
  name: COURSE
  research_supervisor:
  - stevenvs
  tags:
  - active
  - sports
- file: projects/MOOIZO.html
  folder: MOOIZO
  lead_researcher: jellevh
  name: MOoiZO
  research_supervisor:
  - stevenvs
  tags:
  - past
  - healthcare
- file: projects/FAME.html
  folder: FAME
  lead_researcher: kenzomv
  name: FAME
  research_supervisor:
  - stevenvs
  tags:
  - past
  - cultural-heritage
- file: projects/DISSCO.html
  folder: DISSCO
  lead_researcher: kenzomv
  other_researchers:
  - krishnaku
  name: DISSCO
  research_supervisor:
  - stevenvs
  tags:
  - active
  - cultural-heritage
- file: projects/VKC.html
  folder: VKC
  lead_researcher: alecvdb
  name: VKC Enriched
  research_supervisor:
  - stevenvs
  tags:
  - past
  - cultural-heritage
- file: projects/WCN.html
  folder: WCN
  lead_researcher: rodcorte
  name: WCN
  other_researchers:
  - jelledb
  research_supervisor:
  - stevenvs
  tags:
  - active
  - sports
- file: projects/PACE.html
  folder: PACE
  lead_researcher: jelledb
  name: PACE
  research_supervisor:
  - stevenvs
  tags:
  - past
  - sports
- file: projects/hybrid-ai-for-buildings.html
  folder: HYBRID-AI-FOR-BUILDINGS
  lead_researcher: jellevh
  name: HYBRID AI FOR BUILDINGS
  research_supervisor:
  - stevenvs
  tags:
  - past
  - industry
- file: projects/STRADA.html
  folder: STRADA
  lead_researcher: rodcorte
  name: STRADA
  other_researchers:
  - jelledb
  research_supervisor:
  - stevenvs
  - mslembro
  tags:
  - past
  - sports
- file: projects/STATS.html
  folder: STATS
  lead_researcher: rodcorte
  name: STATS
  other_researchers:
  - mslembro
  tags:
  - past
  - sports
- file: projects/VENTOUX.html
  folder: VENTOUX
  lead_researcher: jellevh
  name: VENTOUX
  other_researchers:
  - mslembro
  - rodcorte
  tags:
  - active
  - sports
- file: projects/HENSOR.html
  folder: HENSOR
  lead_researcher: dieterdw
  name: HENSOR
  other_researchers:
  - kenzomv
  - ravikcs
  research_supervisor:
  - stevenvs
  tags:
  - active
  - cultural-heritage
- file: projects/BELGICAWEB.html
  folder: BELGICAWEB
  lead_researcher: ravikcs
  name: BELGICAWEB
  research_supervisor:
  - dieterdw
  tags:
  - active
  - cultural-heritage
- file: projects/METABELGICA.html
  folder: METABELGICA
  lead_researcher: ravikcs
  name: METABELGICA
  research_supervisor:
  - dieterdw
  tags:
  - active
  - cultural-heritage
- file: projects/AI-CARES.html
  folder: AI-CARES
  lead_researcher: dieterdw
  name: AI-CARES
  research_supervisor:
  - dieterdw
  tags:
  - active
  - healthcare
- file: projects/FRIABLE.html
  folder: FRIABLE
  lead_researcher: ravikcs
  name: FRIABLE
  research_supervisor:
  - dieterdw
  tags:
  - past
  - cultural-heritage
- file: projects/COGHENT.html
  folder: COGHENT
  lead_researcher: kenzomv
  name: COGHENT
  research_supervisor:
  - dieterdw
  tags:
  - past
  - cultural-heritage
- file: projects/artemis.html
  folder: ARTEMIS
  lead_researcher: kenzomv
  name: Artemis
  research_supervisor:
  - stevenvs
  tags:
  - active
  - cultural-heritage
- file: projects/SPORSA.html
  folder: SPORSA
  lead_researcher: rodcorte
  name: SPORSA
  research_supervisor:
  - joachimtae
  - stevenvs
  tags:
  - active
  - sports
- file: projects/REPLAY.html
  folder: REPLAY
  lead_researcher: mslembro
  name: RE(P)LAY
  research_supervisor:
  - stevenvs
  tags:
  - active
  - sports
- file: projects/GOTCHA.html
  folder: GOTCHA
  lead_researcher: winter
  name: GOTCHA
  research_supervisor:
  - stevenvs
  tags:
  - active
  - sports
- file: projects/BRIEK.html
  folder: BRIEK
  lead_researcher: winter
  name: BRIEK
  research_supervisor:
  - joachimtae
  - stevenvs
  tags:
  - active
  - sports
- file: projects/endoscopy.html
  folder: ENDOSCOPY
  lead_researcher: jellevh
  name: Endoscopy
  other_researchers:
  - kenzomv
  research_supervisor:
  - stevenvs
  tags:
  - active
  - healthcare
projects_tags:
- active
- past
- cultural-heritage
- geospatial
- sports
- industry
- healthcare
seo:
  description: Welcome to the webpage of our research group. We are a group of researchers
    led by professor Steven Verstockt at Ghent University (IDLab). We mainly focus
    on computer vision aided research. We are involved in projects which are themed
    around cultural-heritage, data-driven sports science and geospatial analysis.
  rel-author: https://s-team-ghent.github.io
  rel-publisher: https://s-team-ghent.github.io
social:
- icon: github
  link: https://github.com/s-team-ghent
- icon: envelope
  link: mailto:steamghent@gmail.com
