#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Welcome to the webpage of our research group. We are a group of researchers led by professor Steven Verstockt at Ghent University (IDLab). We mainly focus on computer vision aided research. We are involved in projects which are themed around cultural heritage, data-driven sports science and geospatial analysis.'
  rel-author: 'https://s-team-ghent.github.io'
  rel-publisher: 'https://s-team-ghent.github.io'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065logo: 
logo:
  url: "./img/triangle.png"
# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

contact: >
  # Contact

  You may contact us through [our team mail address](mailto:steamghent@gmail.com) if you have any questions or would like to bring up any issues.
  You can also find us on the following location

  - UGent Campus Ardoyen

  - Technologiepark-Zwijnaarde 122

  - 9052 Ghent (Zwijnaarde)
#-------------------------------
# Work Section

projects:
- {
    name: 'DAIQUIRI', 
    folder: 'DAIQUIRI', 
    file: "projects/DAIQUIRI.html", 
    lead_researcher: "jelledb",
    other_researchers: ["stevenvs"]
  }
- {
    name: 'SMARTGLAZ', 
    folder: 'SMARTGLAZ', 
    file: 'projects/SMARTGLAZ.html',
    lead_researcher: "jelledb",
    other_researchers: ["stevenvs"]
  }
- {
    name: 'FLORE DE GAND', 
    folder: 'FLORE-DE-GAND', 
    file: 'projects/FLORE-DE-GAND.html',
    lead_researcher: "krishnaku",
    other_researchers: ["stevenvs"]
  }
- {
    name: 'CLUBS', 
    folder: 'CLUBS', 
    file: 'projects/CLUBS.html',
    lead_researcher: "stevenvs",
    other_researchers: ["jelledb"]
  }
- {
    name: 'SPOTT', 
    folder: 'SPOTT', 
    file: 'projects/SPOTT.html',
    lead_researcher: "krishnaku",
    other_researchers: ["stevenvs"]
  }
- {
    name: 'KOERS', 
    folder: 'KOERS', 
    file: 'projects/KOERS.html',
    lead_researcher: "jelledb",
    other_researchers: ["stevenvs"]
  }
- {
    name: 'BASE-X', 
    folder: 'BASE-X', 
    file: 'projects/BASE-X.html',
    lead_researcher: "kenzomv",
    other_researchers: ["stevenvs","jelledb"]
  }
- {
    name: 'TOBIAS', 
    folder: 'TOBIAS', 
    file: 'projects/tobias.html',
    lead_researcher: "jellevh",
    other_researchers: ["stevenvs"]
  }
- {
    name: 'SMART WATERWAYS', 
    folder: 'SMART-WATERWAYS', 
    file: 'projects/smart-waterways.html',
    lead_researcher: "dilawaral",
    other_researchers: ["stevenvs"]
  }
- {
    name: 'BIORACER', 
    folder: 'BIORACER', 
    file: 'projects/bioracer.html',
    lead_researcher: "jarichb",
    other_researchers: ["stevenvs","jelledb"]
  }



#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/s-team-ghent'}
- {icon: 'envelope', link: 'mailto:steamghent@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
