contact: '# Contact

  You may contact us through [our team mail address](mailto:steamghent@gmail.com)
  if you have any questions or would like to bring up any issues. You can also find
  us on the following location

  - UGent Campus Ardoyen

  - Technologiepark-Zwijnaarde 122

  - 9052 Ghent (Zwijnaarde)

  '
disqus:
  comments: false
  disqus_shortname: thathungrymind
google-analytics-ua: UA-112060364-3
logo:
  url: ./img/triangle.png
menu:
- name: Projects
  url: ''
projects:
- file: projects/daiquiri.html
  folder: DAIQUIRI
  lead_researcher: jelledb
  name: DAIQUIRI
  research_supervisor:
  - stevenvs
  tags:
  - active
  - sports
- file: projects/smartglaz.html
  folder: SMARTGLAZ
  lead_researcher: jelledb
  name: SMARTGLAZ
  research_supervisor:
  - stevenvs
  tags:
  - past
  - geospatial
- file: projects/flore-de-gand.html
  folder: FLORE-DE-GAND
  lead_researcher: krishnaku
  name: FLORE DE GAND
  research_supervisor:
  - stevenvs
  tags:
  - active
  - cultural-heritage
- file: projects/hasard.html
  folder: HASARD
  lead_researcher: stevenvs
  name: HASARD
  other_researchers:
  - jelledb
  tags:
  - active
  - sports
- file: projects/spott.html
  folder: SPOTT
  lead_researcher: krishnaku
  name: SPOTT
  research_supervisor:
  - stevenvs
  tags:
  - past
  - cultural-heritage
- file: projects/koers.html
  folder: KOERS
  lead_researcher: jelledb
  name: KOERS
  research_supervisor:
  - stevenvs
  tags:
  - past
  - sports
- file: projects/bas-x.html
  folder: BAS-X
  lead_researcher: kenzomv
  name: BAS-X
  other_researchers:
  - jelledb
  research_supervisor:
  - stevenvs
  tags:
  - past
  - geospatial
- file: projects/tobias.html
  folder: TOBIAS
  lead_researcher: jellevh
  name: TOBIAS
  research_supervisor:
  - stevenvs
  tags:
  - past
  - industry
- file: projects/smart-waterways.html
  folder: SMART-WATERWAYS
  lead_researcher: krishnaku
  name: SMART WATERWAYS
  other_researchers:
  - dilawaral
  research_supervisor:
  - stevenvs
  tags:
  - active
  - industry
- file: projects/bioracer.html
  folder: BIORACER
  lead_researcher: jarichb
  name: BIORACER
  other_researchers:
  - jelledb
  research_supervisor:
  - stevenvs
  tags:
  - past
  - sports
- file: projects/ugesco.html
  folder: UGESCO
  lead_researcher: kenzomv
  name: UGESCO
  other_researchers:
  - dilawaral
  research_supervisor:
  - stevenvs
  tags:
  - past
  - cultural-heritage
  - geospatial
- file: projects/eureca.html
  folder: EURECA
  lead_researcher: dilawaral
  name: EURECA
  other_researchers:
  - kenzomv
  research_supervisor:
  - stevenvs
  tags:
  - past
  - cultural-heritage
- file: projects/DATA-KBR-BE.html
  folder: DATA-KBR-BE
  lead_researcher: dilawaral
  name: DATA-KBR-BE
  research_supervisor:
  - stevenvs
  tags:
  - active
  - cultural-heritage
- file: projects/COURSE.html
  folder: COURSE
  lead_researcher: jelledb
  name: COURSE
  research_supervisor:
  - stevenvs
  tags:
  - active
  - sports
- file: projects/MOOIZO.html
  folder: MOOIZO
  lead_researcher: jellevh
  name: MOoiZO
  research_supervisor:
  - stevenvs
  tags:
  - past
  - healthcare
- file: projects/FAME.html
  folder: FAME
  lead_researcher: kenzomv
  name: FAME
  research_supervisor:
  - stevenvs
  tags:
  - active
  - cultural-heritage
- file: projects/DISSCO.html
  folder: DISSCO
  lead_researcher: krishnaku
  name: DISSCO
  other_researchers:
  - kenzomv
  research_supervisor:
  - stevenvs
  tags:
  - active
  - cultural-heritage
- file: projects/VKC.html
  folder: VKC
  lead_researcher: alecvdb
  name: VKC Enriched
  research_supervisor:
  - stevenvs
  tags:
  - active
  - cultural-heritage
- file: projects/WCN.html
  folder: WCN
  lead_researcher: losimons
  name: WCN
  other_researchers:
  - jelledb
  research_supervisor:
  - stevenvs
  tags:
  - active
  - sports
- file: projects/PACE.html
  folder: PACE
  lead_researcher: jelledb
  name: PACE
  research_supervisor:
  - stevenvs
  tags:
  - active
  - sports
- file: projects/hybrid-ai-for-buildings.html
  folder: HYBRID-AI-FOR-BUILDINGS
  lead_researcher: jellevh
  name: Hybrid AI for buildings
  research_supervisor:
  - stevenvs
  tags:
  - active
  - industry
projects_tags:
- active
- past
- sports
projects_tags:
- active
- past
- cultural-heritage
- geospatial
- sports
- industry
- healthcare
seo:
  description: Welcome to the webpage of our research group. We are a group of researchers
    led by professor Steven Verstockt at Ghent University (IDLab). We mainly focus
    on computer vision aided research. We are involved in projects which are themed
    around cultural-heritage, data-driven sports science and geospatial analysis.
  rel-author: https://s-team-ghent.github.io
  rel-publisher: https://s-team-ghent.github.io
social:
- icon: github
  link: https://github.com/s-team-ghent
- icon: envelope
  link: mailto:steamghent@gmail.com
