contact: '# Contact

  You may contact us through [our team mail address](mailto:steamghent@gmail.com)
  if you have any questions or would like to bring up any issues. You can also find
  us on the following location

  - UGent Campus Ardoyen

  - Technologiepark-Zwijnaarde 122

  - 9052 Ghent (Zwijnaarde)

  '
disqus:
  comments: false
  disqus_shortname: thathungrymind
google-analytics-ua: UA-112060364-3
logo:
  url: ./img/triangle.png
menu:
- name: Projects
  url: ''
- name: Blog
  url: pages/blog
projects:
- file: projects/daiquiri.html
  folder: DAIQUIRI
  lead_researcher: jelledb
  name: DAIQUIRI
  other_researchers:
  - stevenvs
- file: projects/smartglaz.html
  folder: SMARTGLAZ
  lead_researcher: jelledb
  name: SMARTGLAZ
  other_researchers:
  - stevenvs
- file: projects/flore-de-gand.html
  folder: FLORE-DE-GAND
  lead_researcher: krishnaku
  name: FLORE DE GAND
  other_researchers:
  - stevenvs
- file: projects/clubs.html
  folder: CLUBS
  lead_researcher: stevenvs
  name: CLUBS
  other_researchers:
  - jelledb
- file: projects/spott.html
  folder: SPOTT
  lead_researcher: krishnaku
  name: SPOTT
  other_researchers:
  - stevenvs
- file: projects/KOERS.html
  folder: KOERS
  lead_researcher: jelledb
  name: KOERS
  other_researchers:
  - stevenvs
- file: projects/bas-x.html
  folder: BAS-X
  lead_researcher: kenzomv
  name: BAS-X
  other_researchers:
  - stevenvs
  - jelledb
- file: projects/tobias.html
  folder: TOBIAS
  lead_researcher: jellevh
  name: TOBIAS
  other_researchers:
  - stevenvs
- file: projects/smart-waterways.html
  folder: SMART-WATERWAYS
  lead_researcher: dilawaral
  name: SMART WATERWAYS
  other_researchers:
  - stevenvs
- file: projects/bioracer.html
  folder: BIORACER
  lead_researcher: jarichb
  name: BIORACER
  other_researchers:
  - stevenvs
  - jelledb
seo:
  description: Welcome to the webpage of our research group. We are a group of researchers
    led by professor Steven Verstockt at Ghent University (IDLab). We mainly focus
    on computer vision aided research. We are involved in projects which are themed
    around cultural heritage, data-driven sports science and geospatial analysis.
  rel-author: https://s-team-ghent.github.io
  rel-publisher: https://s-team-ghent.github.io
social:
- icon: github
  link: https://github.com/s-team-ghent
- icon: envelope
  link: mailto:steamghent@gmail.com
